config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'
  resources :users
  resources :bands
  resources :movies
  resources :equipments
  resources :environments

  get 'login', to: 'user_sessions#new', as: 'login'
  post 'login', to: 'user_sessions#create'
  post 'logout', to: 'user_sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :band_name, :band_members, presence: true
  mount_uploader :avatar_path, AvatarUploader
end

app/models/environment.rb
class Environment < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :user_name, :student_id, presence: true

  validates :student_id, presence: true,
            format: { with:  /\A^[a-z0-9]+\z/, message: "ID should consist of lowercase letters and numbers(ex: s1300350)" }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }



  def student_judgment
      if student_id.include?("m")
        judgment = 0
      elsif student_id.include?("s")
        judgment = 1
      elsif ["a","b","k"].any?{|i| student_id.include?(i)}
        judgment = 2
      else
        judgment = 3
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: 'Please login first'
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  protect_from_forgery
  before_action :set_band, only: %i[show edit update destroy]

  def index
    @bands = Band.all.order("id")
  end

  def show; end

  def new
    @band = Band.new
    @band.user_id = current_user.id
  end

  def create
    @band = Band.new(band_params)
    @band.user_id = current_user.id
    if @band.save
      redirect_to(:bands, notice: 'Success!')
    else
      flash[:alert] = 'Save error!'
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to(:bands, notice: 'Success!')
    else
      flash[:alert] = 'Save error!'
      render :edit
    end
  end

  def destroy
    @band.destroy
    redirect_to(:bands, notice: 'Success!')
  end

  private

  def set_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:band_name, :band_members, :band_message, :user_id, :avatar_path)
  end
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
    protect_from_forgery
    before_action :set_environment, only: %i[show edit update destroy]

    def index
      @environments = Environment.all.order("id")
    end

    def show; end

    def new
      @environment = Environment.new

    end

    def create
      @environment = Environment.new(environment_params)

      if @environment.save
        redirect_to(:environments, notice: 'Success!')
      else
        flash[:alert] = 'Save error!'
        render :new
      end
    end

    def edit
      @environment = Environment.find(params[:id])
    end

    def update
      @environment = Environment.find(params[:id])
      if @environment.update(environment_params)
        redirect_to(:environments, notice: 'Success!')
      else
        flash[:alert] = 'Save error!'
        render :edit
      end
    end

    def destroy
      @environment.destroy
      redirect_to(:environments, notice: 'Success!')
    end

    private

    def set_environment
      @environment = Environment.find(params[:id])
    end

    def environment_params
      params.require(:environment).permit(:title1,:title2,:title3,:text)
    end

end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all.order("id DESC")
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  protect_from_forgery
  before_action :set_movie, only: %i[show edit update destroy]

  def index
    @movies = Movie.all.order("id DESC")
  end

  def show; end

  def new
    @movie = Movie.new
    @movie.user_id = current_user.id
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    if @movie.save
      redirect_to(:movies, notice: 'Success!')
    else
      flash[:alert] = 'Save error!'
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to(:movies, notice: 'Success!')
    else
      flash[:alert] = 'Save error!'
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to(:movies, notice: 'Success!')
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title,:content, :user_id)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # skip_before_action :require_login, only: [:new, :create]

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  # skip_before_action :require_login, only: [:index, :new, :create]

  # GET /users or /users.json
  def index
    @users = User.order('student_id')
    # @users.division
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @judgment = @user.student_judgment
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = @user.id
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:user_name, :student_id, :email, :password, :password_confirmation, :part, :like_band, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/edit.html.erb
<div class="title">
    <h2 >バンドの編集</h2>
</div>
<div class="allPage">
  <div class="container">
    <%= render 'form', band: @band %>
  </div>
</div>

app/views/bands/index.html.erb
<div class="title">
    <h2 >Band Data</h2>
</div>
<div class="container">
  <div class="row">
      <% @bands.each do |band| %>
        <div class="col-12 col-md-12 col-lg-6" style="margin-top: 40px;">
        <p style="margin-top: 40px;"></p>
        <div style="width:90%; height:40rem;margin:  0 auto; box-shadow: 2px 2px 4px gray;">
          <div class="row">
          <h3 class="col-md-12"  style="text-align: center;"><%= band.band_name %></h3>
          </div>


          <p style="text-align: center;">
              <%= image_tag(band.avatar_path.url, size:'180x180') %>
          </p>

          <div class="text-left" style="margin-bottom: 40px; margin-left: 40px;">
            <strong style="margin-top: 20px;">MEMBERS</strong>
            <div style="height:170px;overflow:auto;">
              <p class="bandSpace">
                <div style="white-space: pre-wrap;margin-left: 20px;"><%= band.band_members%></div>
              </p>
            </div>

            <div>
              <p class="bandSpace">
                <strong>A FEW WORDS</strong>
                <div style="height:60px;overflow:auto;" >　<%= band.band_message %></div>
              </p>
            </div>
          </div>
            <div style=" text-align: center;">
              <% if current_user && current_user.id == band.user_id %>
                <%= link_to "編集",  edit_band_path(band), class: 'btn btn-outline-dark' %>
              <% end %>
            </div>
        </div>
        </div>
      <% end %>
  </div>
  <div class="text-center" style="margin-top: 40px; margin-bottom: 40px;">
      <% if current_user %>
        <%= link_to 'バンドの登録はこちらから' , new_band_path %>
      <% end %>
  </div>
</div>

app/views/bands/new.html.erb
<div class="title">
    <h2 >バンドの登録</h2>
</div>
<div class="allPage">
  <div class="container">
    <%= render 'form' %>
  </div>
</div>

app/views/bands/show.html.erb
<div class="title">
    <h2 >Band</h2>
</div>
<div class="container">
  <p style="margin-top: 40px;"></p>
  <div class="card" style="width: 500px; margin:  0 auto; box-shadow: 2px 2px 4px gray;margin-bottom: 40px;">
    <h3 style="text-align: center;">BAND INTORODUCTION SHEET</h3>

    <p style="text-align: center;">
        <%= image_tag(@band.avatar_path.url, size:'180x180') %>
    </p>

    <div class="text-left" style="margin-bottom: 40px; margin-left: 40px;">

      <p class="bandSpace">
      <strong>BAND NAME</strong>
      <div>　<%= @band.band_name %></div>
      </p>

      <p class="bandSpace">
        <strong>MEMBERS</strong>
        <div style="white-space: pre-wrap;margin-left: 20px;"><%= @band.band_members     %></div>
      </p>

      <p class="bandSpace">
        <strong>A FEW WORDS</strong>
        <div >　<%= @band.band_message %></div>
      </p>
    </div>

    <div style="text-align: center;">
      <%= image_tag 'IMG_6607', size: '50x50'%>
    </div>
  </div>
  <div style="text-align: center;">
    <% if current_user && current_user.id == @band.user_id %>
      <%= link_to 'Edit', edit_band_path(@band) %> |
      <%= link_to 'Destroy', @band, method: :delete, data: { confirm: 'Are you sure'  }    %>|
    <% end %>
      <%= link_to 'Back', bands_path %>
  </div>
</div>

app/views/environments/edit.html.erb
<div class="title">
    <h2 >編集</h2>
</div>
<div class="allPage">
  <div class="container">
    <%= render 'form', environment: @environment %>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'shared/home' %>
<section id="news" class="blog wow fadeInUp" data-wow-delay="300ms">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h2 style="font-size: 5.0vw;">What is CUO?</h2>
                <p class="home1-text">CUOという名前を聞いただけでは、何をするサークルなのかよく分からないですよね？CUOの正式名称は「Comfort Utopian Orchestra」、「お気楽極楽楽団」で す。要するに何でもありの軽音楽系サークルです。
ジャズをやっているバンドがあるかと思えば激しいロックを聴かせてくれるバンドもあったり、 ゲーム音楽をやっちゃったり変な楽器を持ち出して演奏してみたり…それが「音楽」であればあとはその人のやる気次第。 オリジナル曲を演奏している人たちもいたりします。</p>
                <p class="home1-text">「楽しそうだけど、楽器の経験もないし……」と思っている人も いるかと思いますが、心配しなくても大丈夫です。 現在活動中の部員も半分くらいは大学に入ってから楽器を始めていますが、 みんな楽しく演奏活動をしていますよ。 具体的なフォローとしては毎年春に「ごちゃ混ぜバンド演奏会」 というイベントで新入生のバンド初体験をサポートしています。 ですから気後れせずに声をかけてくださいね。気になった方はTwittwerまたはInstagramでDMしてください！</p>
                <ul class="snsbtniti2">
                <a  href="https://twitter.com/CUO_aizu?ref_src=twsrc%5Etfw" class="flowbtn11 fl_tw1"><i class="fab fa-twitter"></i><span>Twitter</span></a>
                <a href="https://www.instagram.com/cuo_aizu/" class="flowbtn11 insta_btn11"><i class="fab fa-instagram"></i><span>Instagram</span></a>
                </ul>
            </div>
            <div class="col-md-5">
                <a class="twitter-timeline" href="https://twitter.com/CUO_aizu?ref_src=twsrc%5Etfw" width="100%;" height="50vw"></a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                <!-- SnapWidget -->
                <ul class="snsbtniti2">
                <a href="https://www.instagram.com/cuo_aizu/" class="flowbtn13 insta_btn13"><i class="fab fa-instagram"></i><span>Instagram</span></a>
                </ul>
                <!-- SnapWidget -->
                <script src="https://snapwidget.com/js/snapwidget.js"></script>
                <iframe src="https://snapwidget.com/embed/984198" class="snapwidget-widget" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden;  width:100%; "></iframe>
            </div>
        </div>
    </div>
</section>
<section id="about" class="number wow fadeInUp" data-wow-delay="300ms">
    <!-- change the image in style.css to the class .number .container-fluid [approximately row 102] -->
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-6 opaline col-md-offset-6">
                    <div class="row">
                        <div class="col-md-offset-1 col-md-10">
                            <h4>CUO Member & Band</h4>
                            <p>入部希望者は，TwitterまたはInstagramでDMください</p>
                            <p><small>入部希望を受け取り次第、CUOのLINEグループに招待いたします。
                            以下が、現在の部員数とバンド数になっています。</small></p>
                        </div>
                    </div>
                    <div class="row text-center">
                        <div class="col-md-4 boxes col-xs-6 col-xs-offset-3 col-lg-4 col-lg-offset-1 col-md-offset-1 col-sm-6 wow fadeInUp">
                            <h5>Members</h5>
                            <h3 class="odometer 01"><%= User.count %></h3>
                        </div>
                        <div class="col-md-4 boxes col-xs-6 col-xs-offset-3 col-lg-4 col-lg-offset-2 col-md-offset-2 col-sm-6 wow fadeInUp" data-wow-delay="300ms">
                            <h5>Bands</h5>
                            <h3 class="odometer 02"><%= Band.count %></h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section id="news" class="blog wow fadeInUp" data-wow-delay="300ms">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <%= image_tag 'jc-120.jpg', class: 'img-responsive' %>
            </div>
            <div class="col-md-7">
                <h4 class="home-title-text">機材</h4>
                <p class="home2-text">機材の詳しい使い方は　”EQUIPMENT”　ページからご覧ください。</p>
                <p class="home2-text">また機材説明を受けていない方の使用は禁止となっております。以下、部室にある主な機材です。</p>
                <p class="home2-text">・Blackstar ID:100 TVP / JC-120 / Ampeg BA-115 / Roland JUNO-G / Roland XV-88 / Drum ...
                <p style="text-align: center; margin-top:50px"><%= link_to "More", equipments_path, class: 'btn btn-outline-dark' %></p>
            </div>
        </div>
    </div>
</section>

<section id="history" class="story wow fadeInUp" data-wow-delay="300ms">
    <!-- change the image in style.css to the class .story .container-fluid [approximately row 141] -->
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-6 opaline">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <p class="lead"><i>CUO Youtube</i></p>
                            <div class="sc">
                                <% @movies.each do |movie| %>
                                    <h6 class="lead"> - <%= movie.title %></h6>
                                    <p><small><%= Rinku.auto_link(movie.content, :all, 'target="_blank"').html_safe %></small></p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="news" class="blog wow fadeInUp" data-wow-delay="300ms">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <%= image_tag 'IMG_6737 2.jpg', class: 'img-responsive' %>
            </div>
            <div class="col-md-7">
                <h4 class="home-title-text">部室</h4>
                <p class="home2-text">部室は厚生棟の三階にあり、そこで個人練習やバンド練習を行っています。興味がある方は
                是非、下のタイムテーブルをみて部員がいる時間帯に覗いてみてください。</p>
                <p class="home2-text">部室の鍵は、厚生棟の警備員室に行き、学生証を提示した上で借りることができます。部室の使い方など、詳しくはこちらのページからご覧ください。</p>
                <p style="text-align: center; margin-top:50px"><%= link_to "More", equipments_path, class: 'btn btn-outline-dark' %></p>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="row">
        <h3 style="text-algin: center;">Time Table</h3>
        <iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;showTz=0&amp;mode=WEEK&amp;height=750&amp;wkst=1&amp;hl=ja&amp;bgcolor=%23FFFFFF&amp;src=aizucuo%40gmail.com&amp;color=%232952A3&amp;src=ja.japanese%23holiday%40group.v.calendar.google.com&amp;color=%23528800&amp;ctz=Asia%2FTokyo" class="col-md-12" style=" border-width:0 " height="800" frameborder="0" scrolling="no"></iframe>
    </div>
</div>

app/views/movies/show.html.erb
<div class="title">
    <h2 >Live Movie</h2>
</div>
<div class="container">
  <p style="margin-top: 40px;"></p>
  <div class="card" style="width: 500px; margin:  0 auto; box-shadow: 2px 2px 4px gray;margin-bottom: 40px;">
    <h3 style="text-align: center;">LIVE MOVIE</h3>
      <p class="bandSpace">
      <strong>TITLE</strong>
      <div>　<%= @movie.title %></div>
      </p>

      <p class="bandSpace">
        <strong>URL</strong>
        <div><%= Rinku.auto_link(@movie.content, :all, 'target="_blank"').html_safe %></div>
      </p>

      <div style="margin:  0 auto;">
      <%= image_tag 'IMG_6607', size: '50x50'%>
      </div>
  </div>
  <div style="text-align: center;">
    <% if current_user && current_user.id == @movie.user_id %>
      <%= link_to 'Edit', edit_movie_path(@movie) %> |
      <%= link_to 'Destroy', @movie, method: :delete, data: { confirm: 'Are you sure'  }    %>|
    <% end %>
      <%= link_to 'Back', movies_path %>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="site-overlay">
    <header class="home">
        <div >
            <div class="container">
                <div class="row">
                    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist" >
                        <li class="nav-item" role="presentation">
                            <%= link_to 'HOME', root_path, class: "nav-link", id: "pills-home-tab",role: "tab", 'aria-controls': 'pills-home', 'aria-selected': :false %>
                        </li>
                        <li class="nav-item" role="presentation">
                            <%= link_to 'MEMBER', users_path, class: "nav-link", id: "pills-profile-tab", role: "tab", 'aria-controls': 'pills-profile', 'aria-selected': :false %>
                        </li>
                        <li class="nav-item" role="presentation">
                            <%= link_to 'BAND', bands_path, class: "nav-link", id: "pills-contect-tab", role: "tab", 'aria-controls': 'pills-contact', 'aria-selected': :false %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "MOVIE", movies_path, class: 'nav-link' %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "EQUIPMENT", environments_path, class: 'nav-link' %>
                        </li>
                    </ul>
                </div>
                <%= render 'shared/nav' %>
            </div>
        </div>
    </header>
</div>

app/views/shared/_home.html.erb
<div class="site-overlay">
    <header id="home">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-2 col-xs-2">
                        <%= link_to image_tag('logo_transparent.png', class: 'img-responsive'), root_path %>
                    </div>
                </div>
                <div class="jumbotron">
                    <p class ="header-title"style="font-size: 300%;font-size: 5vw; margin-top:0px;text-shadow: 1px 1px 1px ">C U O</br>
                    <small>Comfort Utopian Orchestra</small></p>
                    <p style="font-size: 130%; font-size: 1.2vw;text-shadow: 1px 1px 1px ">This is CUO, a music circle at the University of Aizu. <br>
    The official name of the group is Comfort Utopian Orchestra. Let's play music together!</p>
                    <p>
                    <% if current_user %>
                       <%= link_to 'Logout', :logout, method: :post, class: 'btn btn-lg btn-danger', role: 'button' %>
                    <% elsif %>
                        <%= link_to 'Login', login_path, class: 'btn btn-lg btn-primary', role: 'button' %>
                        <%= link_to 'Signup', new_user_path, class: 'btn btn-lg btn-danger', role: 'button' %>
                    <% end %>
                    </p>
                </div>
            </div>
        </div>
    </header>
</div>

app/views/shared/_nav.html.erb
<nav id="nav">
  <ul>
    <li><%= link_to 'HOME', root_path, class: 'dropdown-item' %></li>
    <li><%= link_to 'MEMBER', users_path, class: 'dropdown-item' %></li>
    <li><%= link_to 'BAND', bands_path, class: 'dropdown-item' %></li>
    <li><%= link_to "MOVIE", movies_path, class: 'dropdown-item' %></li>
    <li><%= link_to "EQUIPMENT", environments_path, class: 'dropdown-item'  %></li>
    <% if current_user %>
    <li><%= link_to "PROFILE", user_path(current_user.id), class: 'dropdown-item' %></li>
    <li><%= link_to "LOGOUT", :logout, method: :post, class: 'dropdown-item' %></li>
    <% else %>
    <li><%= link_to "REGISTER", new_user_path, class: 'dropdown-item'%></li>
    <li><%= link_to "LOGIN", :login, class: 'dropdown-item'%></li>
    <% end %>
  </ul>
</nav>
<div id="hamburger">
  <span class="inner_line" id="line1"></span>
  <span class="inner_line" id="line2"></span>
  <span class="inner_line" id="line3"></span>
</div>

<%= javascript_include_tag 'header' %>

app/views/user_sessions/new.html.erb
<div class="title">
    <h2 >Login</h2>
</div>
<div class="container">

  <%= render 'form' %>

  <div style="text-align: center;">
    <%= link_to 'Back', users_path %>
  </div>
  <p style="margin-bottom: 200px;"></p>
</div>

app/views/users/_table.html.erb
  <tr>
    <th><%= link_to user.student_id, user_path(user), class: 'link'%></th>
    <th><%= link_to user.user_name , user_path(user), class: 'link'%></th>
    <th><%= user.part %></th>
  </tr>

app/views/users/edit.html.erb
<div class="title">
    <h2 >Editing User</h2>
</div>
<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="title">
    <h2 >Members</h2>
</div>
<div class="container">
  <p id="notice"><%= notice %></p>
  <div >
    <table class="table tableColor" style="margin-top: 80px;">
      <thead class= "table-dark">
        <tr>
          <th>＜Student Id＞</th>
          <th>＜Name＞</th>
          <th>＜Part＞</th>
        </tr>
      </thead>

      <tbody>
          <tr class="table-secondary"><th colspan="3">・院生</th></tr>
          <% @users.each do |user| %>
            <% if user.student_judgment == 0 %>
              <%= render 'table', user: user %>
            <% end %>
          <% end %>
          <tr class="table-secondary"><th colspan="3">・学部生</th></tr>
          <% @users.each do |user| %>
            <% if user.student_judgment == 1 %>
              <%= render 'table', user: user %>
            <% end %>
          <% end %>
          <tr class="table-secondary"><th colspan="3">・短大生</th></tr>
          <% @users.each do |user| %>
            <% if user.student_judgment == 2 %>
              <%= render 'table', user: user %>
            <% end %>
          <% end %>
          <tr class="table-secondary"><th colspan="3">・その他</th></tr>
          <% @users.each do |user| %>
            <% if user.student_judgment == 3%>
              <%= render 'table', user: user %>
            <% end %>
          <% end %>
      </tbody>
    </table>
  </div>
    <%= link_to 'New User', new_user_path %>
</div>
 </div>

app/views/users/new.html.erb
<div class="title">
    <h2 >New User</h2>
</div>
<div class="container">

  <%= render 'form', user: @user %>

  <div style="text-align: center;">
    <%= link_to 'Back', users_path %>
  </div>
</div>

app/views/users/show.html.erb
<div class="title">
    <h2 >Profile</h2>
</div>
<p id="notice"><%= notice %></p>
<div class="container">
  <p style="margin-top: 40px;"></p>
  <div class="card" style="width: 500px; margin:  0 auto;box-shadow: 2px 2px 4px gray;margin-bottom: 40px;">
    <h3 style="text-align: center;">PROFILE SHEET</h3>
    <div class="text-left" style="margin-bottom: 40px; margin-left: 40px;">

      <p class="bandSpace">
      <strong>NAME</strong>
      <div>　<%= @user.user_name %></div>
      </p>

      <p class="bandSpace">
        <strong>STUDENT ID</strong>
        <div >　<%= @user.student_id%></div>
      </p>

      <p class="bandSpace">
        <strong>PART</strong>
        <div >　<%= @user.part %></div>
      </p>

      <p class="bandSpace">
        <strong>FAVORITE BAND</strong>
        <div style="white-space: pre-wrap;margin-left: 20px;"><%= @user.like_band %></div>
      </p>

      <p class="bandSpace">
        <strong>MESSAGE</strong>
        <div style="white-space: pre-wrap;margin-left: 20px;"><%= @user.message %></div>
      </p>
    </div>
    <div style=" margin:  0 auto;">
      <%= image_tag 'IMG_6607', size: '50x50'%>
      </div>
  </div>

  <div style="text-align: center;">
    <% if @user == current_user %>
    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure'   }   %>|
    <% end %>
    <%= link_to 'Back', users_path %>
  </div>
</div>